"""Versionado semántico del programa (independiente del control de versiones del código)."""

__version__ = "0.29.0"

# Historial resumido — el detalle completo vive en CHANGELOG.md
VERSION_NOTES = {
    "0.1.0": "Primera fase: login por certificado/contraseña, gestión de usuarios, "
              "y flujo completo de Formato de Requerimientos (Agente del PAE y Abogado).",
    "0.2.0": "Súper-usuario y Administrador se siembran automáticamente (una sola vez, "
              "sin importar la máquina); cambio de contraseña obligatorio para el Abogado "
              "en su primer inicio de sesión o tras un reset; tecla Enter vinculada al "
              "botón 'Iniciar sesión' en las pantallas de login.",
    "0.3.0": "Los datos de identidad (usuario/nombre/correo) del Administrador y del "
              "súper-usuario ya pueden cambiarse desde el programa, siempre confirmando "
              "con el certificado ACTUAL de la cuenta afectada; el cambio obliga a generar "
              "un certificado nuevo. El archivo de sembrado del súper-usuario/Administrador "
              "ahora viaja cifrado dentro del .exe.",
    "0.4.0": "Respaldo automático de pae.db antes de cualquier migración de esquema; "
              "nueva pestaña 'Trazabilidad' (sólo Administrador/súper-usuario) para "
              "importar en modo sólo lectura el pae.db de otra máquina y revisar qué se "
              "importó/capturó, cuándo y por quién; se corrigió que el import del Abogado "
              "no quedaba registrado en el historial de archivos importados.",
    "0.4.1": "Corrección: el Agente del PAE ya no importa en silencio. Si un archivo "
              "no tiene filas de datos (p. ej. porque no tiene fila final de totales) "
              "o no se pudo leer (formato inválido/.xls antiguo), ahora se muestra un "
              "aviso claro en vez de no hacer nada.",
    "0.5.0": "El Agente del PAE ya puede importar archivos .xls antiguos, además de "
              ".xlsx. Cada archivo subido queda registrado de inmediato en el histórico "
              "(quién, cuándo, cuántas filas), sin límite de repeticiones -- el aviso de "
              "'archivo duplicado' ahora sólo aplica dentro del lote que se está "
              "preparando en ese momento para el Abogado, nunca contra el histórico completo.",
    "0.5.1": "Corrección importante: la base de datos usaba el modo WAL de SQLite, "
              "que guarda cambios recientes en archivos adicionales (pae.db-wal, "
              "pae.db-shm) aparte de pae.db. Como el programa se distribuye copiando "
              "la carpeta data/ a mano entre computadoras, copiar sólo pae.db (o "
              "copiar mientras el programa seguía abierto) podía dejar una copia "
              "con cuentas/contraseñas desactualizadas -- pae.db ahora es siempre "
              "el único archivo con la verdad completa (modo DELETE); las bases ya "
              "creadas se convierten automáticamente la primera vez que se abren "
              "con esta versión.",
    "0.6.0": "El programa ahora revisa, justo después de cada inicio de sesión, si hay "
              "una versión más nueva publicada en GitHub; si la hay, pregunta si se "
              "quiere instalar y, de aceptar, la descarga y se reemplaza sola "
              "(usando un ayudante updater.exe incluido junto al programa). Si no hay "
              "internet o algo falla en la consulta, no aparece ningún aviso y el "
              "programa sigue igual que siempre. Las instalaciones anteriores a la "
              "0.6.0 no tienen ese ayudante todavía, así que este primer salto debe "
              "hacerse una vez de forma manual, como antes.",
    "0.7.0": "Nueva pestaña 'Bienvenida' al iniciar sesión (para todos los roles), con la "
              "imagen de Apariencia mostrada completa y sin deformarse (antes se estiraba "
              "sin respetar proporción). Cajas y pestañas ahora tienen un fondo semi-opaco "
              "para que el texto no se pierda contra la imagen de fondo. El Agente del PAE "
              "y el Abogado ya no ven la pestaña de Requerimientos siempre abierta: se "
              "accede desde un nuevo menú 'Formato', y ambos ganan una pestaña simplificada "
              "de 'Datos de cuenta' para actualizar su correo. En Trazabilidad se agregó un "
              "botón para cerrar el archivo que se está revisando. Se corrigió que la "
              "ventana principal no se pudiera redimensionar libremente a lo alto tras "
              "iniciar sesión.",
    "0.7.1": "Las pestañas de Formato de Requerimientos/Mandamientos (Agente del PAE y "
              "Abogado) ya se pueden cerrar. 'Datos de cuenta' se movió de pestaña fija a "
              "un nuevo menú 'Otros'. Nuevo menú 'Ver como' para el Súper-usuario: elige un "
              "Agente del PAE o Abogado y ve su pantalla en modo simulación, sin guardar "
              "nada de lo que haga ahí. En el login se agregó un botón 'Regresar' para "
              "volver a escribir el usuario. Corrección adicional al redimensionado: la "
              "hoja de estilos ya no se aplica directamente sobre la ventana principal "
              "(causa más probable de que sólo se pudiera ajustar a lo ancho).",
    "0.8.0": "Corregido un bug de arranque en el login (Enter disparaba, en segundo "
              "plano, la acción de una página oculta -- por eso a veces mandaba a "
              "'Olvidé mi contraseña' sin haberlo pedido). El Abogado captura ahora dos "
              "eventos separados: Fecha/Recibe de CITATORIO y Fecha/Quién recibe de "
              "NOTIFICACIÓN. El archivo que el Agente exporta para el Abogado se llama "
              "'LISTA DEL {fecha} {abogado}'. Nuevo: el Agente puede importar la captura "
              "que el Abogado exportó y marcar PROCEDE/NO PROCEDE por fila, con su propia "
              "exportación. Nuevo menú 'Histórico' (Agente y Abogado) con los archivos que "
              "han cargado. La exportación del Abogado agrega 'ENTREGA {fecha}' al nombre "
              "y ofrece enviarla por correo al Agente del lote, o sólo exportarla.",
    "0.9.0": "Nuevo código de respaldo para Súper-usuario y Administrador: se muestra una "
              "sola vez al generar el certificado y permite recuperar el acceso de "
              "inmediato desde el login si se pierde o daña el certificado, sin depender "
              "de la aprobación de nadie más. Las cuentas ya existentes pueden generar uno "
              "desde 'Datos de cuenta'. Corregido además que la solicitud de 'Olvidé mi "
              "contraseña o certificado' del propio Administrador se dirigía a sí mismo "
              "(ahora se dirige al Súper-usuario, como respaldo adicional).",
    "0.10.0": "El certificado anterior ya se borra automáticamente de donde se había "
              "guardado cuando se genera uno nuevo (antes quedaba huérfano tras cambiar "
              "de usuario, por ejemplo). Nuevo botón 'Generar después' al generar "
              "certificado, que cierra la sesión de inmediato en vez de dejarla a medias. "
              "Cada rol con certificado (Súper, Administrador, Agente del PAE) puede "
              "generar uno nuevo por su cuenta desde Datos de cuenta, y el Abogado ya "
              "puede cambiar su propia contraseña ahí mismo.",
    "0.10.1": "El Súper-usuario y el Administrador ya ven también los datos del "
              "Administrador en la pantalla 'Usuarios', junto a Agentes del PAE y "
              "Abogados. Sigue siendo sólo de consulta: es una cuenta única, no se da de "
              "alta ni se edita desde ahí.",
    "0.11.0": "La revisión de actualizaciones ahora corre antes del login, no después. "
              "Nuevo instalador SistemaPAE_Setup.exe para primeras instalaciones (instala "
              "el Redistribuible de Visual C++ si falta, evitando la interfaz sin texto/"
              "fondos; deja accesos directos). Nuevo: certificado \"maestro\" del "
              "súper-usuario, reconocido desde el primer arranque en cualquier máquina "
              "nueva, sin enrolar uno distinto en cada una.",
    "0.12.0": "Nuevo formato propio .mcdiep para el intercambio de Requerimientos entre "
              "Agente del PAE y Abogado, en vez de Excel: no se puede editar a mano. La "
              "exportación del Agente para el Abogado queda firmada con su certificado y "
              "atada a un Abogado específico -- al importarla se muestra quién firmó, y si "
              "la firma no es válida o es para otro Abogado, no se abre. La exportación del "
              "Abogado para el Agente también pasa a .mcdiep, sin firma.",
    "0.12.1": "La exportación (Agente y Abogado) ahora deja elegir la carpeta de destino en "
              "vez de guardar siempre en la carpeta interna del programa. Confirmado con "
              "pruebas: la verificación del certificado al exportar como Agente rechaza "
              "correctamente contraseña incorrecta y certificado de otra cuenta, sin crear "
              "el lote en ninguno de los dos casos.",
    "0.13.0": "Corregidas las fechas y horas que se mostraban en formato aaaa-mm-dd y en "
              "hora UTC (no la del equipo) en Histórico, Trazabilidad, solicitudes de "
              "reset y la lista de lotes del Abogado: ahora se muestran en hora local, "
              "formato dd/mm/aaaa. Nuevo para el Abogado: botón 'Finalizar captura' que "
              "guarda el lote como terminado y bloquea sus filas para que no se puedan "
              "modificar por accidente; 'Editar captura' lo desbloquea de nuevo. La "
              "exportación del Abogado ya sólo incluye las filas que capturó -- las que "
              "quedaron vacías (tal como se importaron) ya no se exportan.",
    "0.14.0": "Corregido: tras cancelar la selección de certificado en el login y "
              "presionar 'Regresar', Enter dejaba de funcionar en la pantalla de usuario "
              "(el clic sí funcionaba) -- el foco no se recuperaba a tiempo tras cerrar el "
              "diálogo nativo. El Agente ahora ve la lista de archivos Excel cargados en el "
              "lote y debe confirmarla antes de exportar (si cancela, no se pierde lo ya "
              "cargado). Ambas exportaciones (Agente y Abogado) avisan y piden confirmar "
              "antes de sobrescribir un archivo con el mismo nombre. La revisión de captura "
              "del Abogado ahora guarda y muestra, hasta la derecha, el ID del Abogado al "
              "que pertenece. Las columnas de las tablas del Agente ya se pueden "
              "redimensionar arrastrando el borde. Se optimizó el refresco de las tablas "
              "grandes (import/revisión del Agente y captura del Abogado) para que no se "
              "sientan lentas al crecer.",
    "0.15.0": "El mensaje que se muestra cuando falla la verificación de un certificado "
              "(al iniciar sesión o al confirmar identidad antes de exportar) ya no revela "
              "si la contraseña ingresada era correcta -- antes, probar un certificado que "
              "no era el de la cuenta con la contraseña correcta mostraba un mensaje "
              "distinto ('no corresponde a este usuario') al de una contraseña incorrecta, "
              "lo que permitía confirmar si se acertó la contraseña de un certificado ajeno. "
              "Ahora el mensaje es siempre el mismo, sin importar la causa real del rechazo.",
    "0.16.0": "Nueva pantalla de login con el escudo del Municipio de Celaya de fondo "
              "(ajustado al tamaño de la ventana, sin deformarse) y el mensaje de "
              "bienvenida al Sistema de Control del Proceso Administrativo de Ejecución "
              "(SICPAE). Todos los títulos de ventana siguen ahora el mismo formato: "
              "'{nombre de la ventana} - SICPAE v#.##.##'. Corregido: cuando el FOLIO se "
              "guarda como número en el Excel de origen, ya no aparece con '.0' al final "
              "al importarlo.",
    "0.16.1": "Corregido: en la pantalla de login, el texto de las páginas de usuario, "
              "contraseña y certificado no tenía fondo opaco y se perdía contra las zonas "
              "claras del escudo. Ahora todas las etiquetas de esas páginas tienen el mismo "
              "fondo semi-opaco que ya tenía el mensaje de bienvenida.",
    "0.17.0": "Nuevo botón 'Buscar' (por FOLIO, CTA PREDIAL o CONTRIBUYENTE) en la captura "
              "del Abogado y en la revisión del Agente, que posiciona y resalta la fila "
              "encontrada. Los lotes del Abogado ahora se muestran en pestañas Pendientes/"
              "Exportados/Finalizados, moviéndose sola cada una según su estado. Un lote "
              "queda bloqueado automáticamente en cuanto se exporta -- para editarlo de "
              "nuevo hay que usar 'Editar captura', que ahora avisa si ese lote ya se había "
              "exportado antes (el archivo ya entregado no se actualiza solo).",
    "0.18.0": "El menú Formato del Agente del PAE ahora tiene dos pantallas separadas: "
              "'Generar formato' (subir Excel y exportar para el Abogado) y 'Revisar "
              "formato de abogado' (importar la captura y marcar PROCEDE/NO PROCEDE), en "
              "vez de una sola pantalla con todo apilado. La pantalla de revisión muestra "
              "el nombre del archivo que se está revisando, tanto en una etiqueta como en "
              "el título de su pestaña. En la vista del Abogado se quitaron las pestañas "
              "Pendientes/Exportados/Finalizados: ahora hay una pantalla previa con un "
              "combo para elegir el tipo de documento (Pendiente/Exportado/Finalizado), "
              "que lista los lotes de ese tipo; un botón 'Abrir' carga el seleccionado en "
              "la tabla y otro 'Limpiar' vacía la lista y cierra lo abierto. Cambiar el "
              "tipo directamente también vacía la lista mostrada.",
    "0.18.1": "El menú Formato del Agente del PAE se reorganizó en submenús: 'Generar "
              "Formato' y 'Revisar Formato', cada uno con 'Requerimiento' y 'Mandamiento "
              "(Próximamente)' -- este último ya preparado en el menú aunque todavía no "
              "esté desarrollado. Las pestañas correspondientes ahora se llaman 'Generar "
              "Formato Requerimiento', 'Generar Formato Mandamiento', 'Revisar Formato "
              "Requerimiento' y 'Revisar Formato Mandamiento'.",
    "0.19.0": "Corregido: en 'Revisar Formato Requerimiento', importar varios archivos "
              "de captura del Abogado los iba concatenando en una sola tabla -- ahora cada "
              "archivo importado queda separado, y la tabla sólo muestra el que se abrió. "
              "Nueva pantalla previa con un combo Pendiente/Revisado: lista los archivos "
              "importados según si ya se marcó PROCEDE/NO PROCEDE en todas sus filas o no, "
              "para saber de un vistazo qué entregas del Abogado faltan por revisar.",
    "0.20.0": "Nuevo menú 'Seguimiento' para el Agente del PAE: reúne en una sola pantalla "
              "los documentos en sus 4 etapas -- GENERADOS (lo exportado en 'Generar "
              "Formato'), EN REVISIÓN, PENDIENTES DE ENVIAR COMO REPORTE y REPORTES "
              "ENVIADOS (estas 3 últimas, del ciclo de 'Revisar Formato') -- con la fecha "
              "en que se cargó cada uno y la de su último cambio de estatus. Con doble "
              "clic o el botón de acción: en GENERADOS, vuelve a exportar el documento "
              "(pidiendo confirmación, certificado, y dónde guardarlo con qué nombre); en "
              "EN REVISIÓN, abre ese archivo directamente en 'Revisar Formato "
              "Requerimiento' para continuar marcando PROCEDE/NO PROCEDE. La exportación "
              "como reporte (PENDIENTES DE ENVIAR -> REPORTES ENVIADOS) todavía no está "
              "disponible -- se necesita más planeación para esa fase.",
    "0.20.1": "Corrección: en una instalación nueva (base de datos vacía), las ventanas "
              "del programa (Bienvenida, Agente, Abogado, etc.) se veían sin imagen de "
              "fondo -- sólo el login la traía. Ahora, si el Administrador nunca ha "
              "configurado una apariencia en 'Otros > Apariencia' en esa máquina, se usa "
              "un fondo de fábrica por defecto; si el Administrador eligió una imagen o "
              "un color propio, esa elección se sigue respetando sin cambios.",
    "0.21.0": "Contadores en la captura del Abogado (Total de la lista/Total de "
              "llenados/Faltan por llenarse, según la columna QUIÉN RECIBE); nueva opción "
              "'HOJA DE CAMPO' en Recibe citatorio/Quién recibe. Exportación en PDF junto "
              "al .mcdiep en las tres exportaciones (Generar Formato, captura del Abogado, "
              "y 'Volver a exportar' de Seguimiento): hoja horizontal con cabecera "
              "institucional, contadores de notificación, todas las columnas ajustadas al "
              "ancho de la página, y un sello estilo CFDI con UUID, hash SHA-256, firma "
              "digital (cuando hay certificado) y un código QR -- en la primera página "
              "dentro de la cabecera, en las siguientes al pie. El UUID y el hash quedan "
              "embebidos en el propio .mcdiep y guardados en la base de datos de quien "
              "exporta; al importar (Abogado o Agente en Revisar Formato) se muestran en "
              "pantalla para comparar visualmente contra el PDF físico recibido. El nombre "
              "sugerido de los archivos exportados ahora sigue el patrón "
              "AGENTE_ABOGADO_UUID_HASH fecha.",
    "0.21.1": "Corregido: el botón 'Generar Formato > Requerimiento' del Agente del PAE "
              "no hacía nada al hacer clic en la versión instalada (.exe empacada) -- "
              "reportlab importa por dentro el módulo del código QR de forma dinámica, y "
              "el empaquetado no lo estaba incluyendo, así que fallaba en silencio al "
              "abrir esa pantalla. Ya viene incluido. Además, cualquier error inesperado "
              "en un clic ahora se registra en data/error.log y se avisa en pantalla, en "
              "vez de no hacer nada visible como antes.",
    "0.21.2": "El instalador y el .exe pesan alrededor de 20 MB menos (de ~77 a "
              "~56 MB): se quitaron del empaquetado numpy (nunca se usa en el "
              "programa -- se colaba como dependencia opcional de Pillow), los "
              "componentes de Qt para pantallas QML/táctiles y teclado virtual "
              "(el programa es de escritorio con teclado físico, sin ninguna "
              "pantalla de ese tipo), el lector de PDF-como-imagen de Qt (los PDF "
              "se generan con reportlab, nunca se abren dentro del programa), y "
              "las traducciones de Qt a otros idiomas (todo el texto del programa "
              "ya está en español, fijo en el código). Sin cambios de "
              "funcionalidad -- verificado que el sello con QR de los PDF sigue "
              "generándose y leyéndose igual.",
    "0.22.0": "Nuevo módulo de Mandamiento, con el mismo flujo completo que "
              "Requerimiento (generar/revisar del Agente del PAE, captura y "
              "exportación del Abogado, seguimiento, histórico y trazabilidad), "
              "en tablas y pantallas propias -- ya no es 'Próximamente'. La "
              "única diferencia real: su Excel de origen sólo trae FOLIO, CTA "
              "PREDIAL y CONTRIBUYENTE (columnas B, C y D) -- no hay DOMICILIO. "
              "El PDF que lo acompaña lleva su propio encabezado institucional "
              "('FORMATO: ENTREGA DE MANDAMIENTOS DE EJECUCIÓN').",
    "0.23.0": "Nueva paleta institucional en toda la interfaz (verde #3A6B46 "
              "como color de uso diario -- barras, pestaña activa, botones -- "
              "guinda #8A1E2D para acciones críticas como Exportar/Firmar y "
              "para los encabezados de tabla, ocre #A67242 en bordes y "
              "separadores). Se extendió el estilo al login y a los diálogos "
              "(certificado, contraseña, recuperación, enrolamiento), que "
              "antes no tenían ningún estilo propio. El encabezado de la "
              "tabla en el PDF exportado (Requerimiento y Mandamiento) ahora "
              "es guinda en vez de azul, igual que en pantalla.",
    "0.24.0": "Nueva pestaña 'Colores' (Administrador/Súper-usuario), junto a "
              "'Apariencia': permite personalizar los 3 colores base del "
              "programa (identidad, crítico, estructura) escribiendo el "
              "código hexadecimal deseado. 'Aplicar (vista previa)' prueba "
              "los colores de inmediato en TODAS las ventanas abiertas, sin "
              "guardarlos -- se pierden al reiniciar el programa si no se "
              "confirman. 'Restaurar predeterminados' vuelve en cualquier "
              "momento a la combinación de fábrica (verde/guinda/ocre). "
              "'Guardar como predeterminado' (con advertencia, porque cambia "
              "el programa entero y no se puede deshacer) deja los colores "
              "fijos de forma permanente -- se guardan en la base de datos, "
              "así que se mantienen incluso después de actualizar el "
              "programa. El encabezado de tabla del PDF también sigue el "
              "color crítico guardado (nunca una vista previa sin confirmar).",
    "0.25.0": "En la pestaña 'Colores', el botón único 'Guardar como "
              "predeterminado' se separó en dos: 'Guardar cambios de "
              "interfaz' (sólo pantalla -- menús, botones, pestañas) y "
              "'Guardar cambios del PDF' (sólo el encabezado de los PDF "
              "exportados), cada uno con su propia advertencia de "
              "confirmación. Ahora se pueden ajustar los colores de "
              "pantalla al gusto de quien usa el programa en esa "
              "computadora sin arriesgar que un PDF oficial salga con un "
              "color distinto al ya aprobado -- el color del PDF sólo "
              "cambia cuando se guarda explícitamente con su propio botón. "
              "Se agregó además una etiqueta que muestra el color "
              "actualmente guardado para el encabezado del PDF.",
    "0.26.0": "El Agente del PAE ya tiene su propio acceso a 'Colores' "
              "(menú Otros): puede ajustar los colores de SU interfaz a su "
              "gusto -- 'Restaurar predeterminados', 'Aplicar (vista "
              "previa)' y 'Guardar cambios de interfaz', igual que "
              "Administrador/Súper-usuario, pero sin el botón para cambiar "
              "el color del PDF (eso sigue siendo exclusivo de "
              "Administrador/Súper-usuario, porque el PDF es un documento "
              "oficial). El Abogado no tiene acceso a 'Colores': siempre "
              "ve la interfaz con lo que esté guardado en ese momento, sin "
              "poder cambiarlo.",
    "0.27.0": "Nuevas cuentas de prueba para el piloto alpha con usuarios "
              "finales: 'agente_dummy' y 'abogado_dummy', contraseña "
              "'dummy12345' -- se crean solas en cualquier instalación, "
              "igual que el súper-usuario/Administrador. Con ellas se "
              "puede probar el flujo completo de Generar/Revisar/Capturar "
              "Requerimientos y Mandamientos, pero nada de lo que se haga "
              "se guarda (modo simulación forzado, como en 'Ver como'). "
              "Tampoco se puede cambiar su correo, contraseña ni "
              "certificado desde 'Datos de cuenta', ni guardar cambios de "
              "color desde 'Colores' (agente_dummy) -- para que la cuenta "
              "compartida siga siendo utilizable indefinidamente con la "
              "misma contraseña. El título de la ventana avisa 'CUENTA DE "
              "PRUEBA, NADA SE GUARDA' mientras se usan.",
    "0.28.0": "'Generar Formato' (Requerimiento y Mandamiento) para las "
              "cuentas de prueba ('agente_dummy') ahora genera un archivo "
              "real (.mcdiep + PDF) en vez de simularlo por completo: sin "
              "certificado ni firma, acotado a una sola página (máximo 8 "
              "filas), con UUID y Hash mostrando 'USUARIO PRUEBA' en vez de "
              "un identificador real, sin código QR, y con una marca de "
              "agua diagonal 'PAE PRUEBA - {nombre del agente}' en toda la "
              "hoja. Sigue sin guardarse nada en la base de datos -- el "
              "archivo generado sólo sirve para revisar visualmente el "
              "formato. 'Revisar Formato' y la captura del 'abogado_dummy' "
              "siguen en modo simulación completa (sin archivo real).",
    "0.29.0": "'Generar Formato' (Requerimiento y Mandamiento) del Agente "
              "del PAE ahora exporta también un .xlsx de respaldo, junto al "
              ".mcdiep y el PDF ya existentes -- mismos datos exportados, "
              "en un formato universal que se puede abrir con cualquier "
              "hoja de cálculo. Es una medida adicional de control: si el "
              ".mcdiep se daña, se pierde o algo falla en el programa, el "
              ".xlsx conserva un respaldo legible de lo que se exportó. No "
              "reemplaza al .mcdiep -- el Abogado lo sigue necesitando "
              "para importar dentro del programa. Esto no aplica a las "
              "exportaciones de prueba de 'agente_dummy' (siguen siendo "
              "sólo .mcdiep + PDF de una página).",
}
