"""Constantes globales: roles, tipos de autenticación y estados."""

from app.__version__ import __version__

APP_NAME = "Sistema PAE"
SICPAE_NAME = "SICPAE"


def window_title(name: str) -> str:
    """Formato estándar del título de toda ventana: '{nombre} - SICPAE v#.##.##'."""
    return f"{name} - {SICPAE_NAME} v{__version__}"

ROLE_SUPERUSUARIO = "SUPERUSUARIO"
ROLE_ADMINISTRADOR = "ADMINISTRADOR"
ROLE_AGENTE_PAE = "AGENTE_PAE"
ROLE_ABOGADO = "ABOGADO"

ROLES = (ROLE_SUPERUSUARIO, ROLE_ADMINISTRADOR, ROLE_AGENTE_PAE, ROLE_ABOGADO)

ROLE_LABELS = {
    ROLE_SUPERUSUARIO: "Súper-usuario",
    ROLE_ADMINISTRADOR: "Administrador",
    ROLE_AGENTE_PAE: "Agente del PAE",
    ROLE_ABOGADO: "Abogado",
}

# Roles que se autentican con certificado autofirmado (vs. usuario/contraseña)
CERT_ROLES = (ROLE_SUPERUSUARIO, ROLE_ADMINISTRADOR, ROLE_AGENTE_PAE)
PASSWORD_ROLES = (ROLE_ABOGADO,)

AUTH_TYPE_CERTIFICADO = "CERTIFICADO"
AUTH_TYPE_PASSWORD = "PASSWORD"

# Roles que además pueden actuar como Agente del PAE
ROLES_CAN_ACT_AS_AGENTE = (ROLE_SUPERUSUARIO, ROLE_ADMINISTRADOR)

BATCH_STATUS_PENDIENTE_ABOGADO = "PENDIENTE_ABOGADO"
BATCH_STATUS_CAPTURADO = "CAPTURADO"
BATCH_STATUS_EXPORTADO = "EXPORTADO"

QUIEN_RECIBE_EN_PUERTA = "EN PUERTA"
QUIEN_RECIBE_NOMBRE = "NOMBRE"

RESET_REASON_CONTRASENA = "CONTRASENA_OLVIDADA"
RESET_REASON_CERTIFICADO_PERDIDO = "CERTIFICADO_PERDIDO"
RESET_REASON_CERTIFICADO_VENCIDO = "CERTIFICADO_VENCIDO"

RESET_REASON_LABELS = {
    RESET_REASON_CONTRASENA: "Contraseña olvidada",
    RESET_REASON_CERTIFICADO_PERDIDO: "Certificado perdido/dañado",
    RESET_REASON_CERTIFICADO_VENCIDO: "Certificado vencido",
}

RESET_STATUS_PENDIENTE = "PENDIENTE"
RESET_STATUS_ATENDIDA = "ATENDIDA"

ADMIN_NOTIFICATION_EMAIL_SUBJECT = "Solicitud de cambio de contraseña o certificado"
